### ISSUE TITLE
音檔116~120錯亂

### ISSUE THREAD

**Issue by Ka-lip** [yiufung/minnan-700#1]
`minnan700-116-翕相.mp3` 的發音有2個，但音檔切錯了，造成116~121錯亂了...
@yiufung

**Comment by yiufung** [comment]
謝謝報錯！好的，等我有時間研究一下。如果你有時間，可以提交一個PR，我會merge進來

**Comment by smailzhu** [comment]
[labels/computed_labels.txt](https://github.com/yiufung/minnan-700/blob/ebe7093/labels/computed_labels.txt) 的時間跟 [mp3/all_pages.mp3](https://github.com/yiufung/minnan-700/blob/ebe7093/mp3/all_pages.mp3) 好像對不太起來，請問是這兩個檔案來分割個別單字的音檔嗎？

**Comment by yiufung** [comment]
按道理應該是這兩個檔案的。不過我看了一下，似乎對不上了，可能是我當年使用了 truncate silence 之類的插件但是沒有記下參數……

如果只是少數幾個文件出錯的話，我想最快的方法是重命名文件吧。我把原本壓縮的單字文檔全部解壓到新增的 `splitted_audio` 文件夾裏了，可否請你們重命名後提交PR？

**Comment by Ka-lip** [comment]
好  我是複習anki時發現的 我想可能也有其他地方錯亂
我全部聽完後再一次整包改

**Comment by Ka-lip** [comment]
hi @yiufung 
我其實不太會用git, 但我目前改好了.
`git push --set-upstream origin fix_audio`　時被拒絕, 可以請你教我怎麼做嗎?
Error messages:

```git
ERROR: Permission to yiufung/minnan-700.git denied to Ka-lip.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

(Branch name is fix_audio)
謝謝!!

**Comment by yiufung** [comment]
Hi @Ka-lip 
謝謝你願意貢獻給這個項目。

因你沒有我的項目的direct access，就會遇到以上的錯誤。你需要先fork一份到自己的github下，即成爲Ka-lip/minnan-700, 將你的更動push到 *你自己* 的fork repo裏，之後在GitHub網頁的Pull Requests頁面來提交merge。

再次謝謝你對這個項目的關注和支持 :)
