### ISSUE TITLE
更新至anki web

### ISSUE THREAD

**Issue by Ka-lip** [yiufung/minnan-700#3]
@yiufung 
Hi 大大，又是我不好意思~
想跟您請教anki web上面share的deck有辦法更新嗎??
最近有些朋友問我要怎麼學台語，我想推薦他們這個deck，但對素人來說github有點複雜。我看anki web上的deck好像還是舊的...想請問能否更新。謝謝!!

https://ankiweb.net/shared/info/1891161765

**Comment by yiufung** [comment]
Hi 你好，謝謝你的關注和推薦，上次更正之後我也試過更新ankiweb的版本，但是好像沒有提供這個功能 :/
如果你不怕麻煩，歡迎在ankiweb上載一個新的版本 :)

**Comment by Ka-lip** [comment]
@yiufung 
hi 謝謝您的回覆.
我剛查了一下好像是可行的，只是要麻煩用你當初的帳號更新. 不知道您是否試過這個方法呢?? 謝謝.
https://docs.ankiweb.net/contrib.html?highlight=share#sharing-decks-publicly

**Comment by yiufung** [comment]
@Ka-lip 謝謝你！根據你發的文檔鏈接指引，已經成功更新了AnkiWeb上的版本。原來是通過這樣的方式，之前沒有留意到。

目前AnkiWeb上的版本和GitHub是同步的了。歡迎測試，如果還有問題我再修改。再次感謝你的關注和協助！
